# To build the image, use this command
# docker build --build-arg PASSWORD=ethereum -t elysianempire/ethereum-miner .
# Delete all containers
# docker rm --force `docker ps -qa`
ethereum-data:
  container_name: ethereum-data
  image: elysianempire/ethereum
  volumes:
    - /home/ethereum/
ethereum-miner:
  container_name: ethereum-miner
  image: elysianempire/ethereum
  volumes_from:
    - ethereum-data
  ports:
    - "30303:30303"
    - "8545:8545"
  command: geth --rpc --rpcaddr "0.0.0.0" --mine
